// <auto-generated />
namespace WebApplication1illustrios_Blog_Task.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ali : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ali));
        
        string IMigrationMetadata.Id
        {
            get { return "202012221336166_ali"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
